### ISSUE TITLE
Correctly handle private repositories

### ISSUE THREAD

**Issue by bellons91** [Maximinodotpy/Gitdown#2]
When specifying a git repository in the plugin, you should handle the case of a private repository.

As of now, if the repository is private, the whole WP-ADMIN page breaks with no information about the error.

So, I suggest 2 approaches:

1. handle the exception to prevent WP from breaking (and explicitly write that the repository **must** be public)
2. handle authentication to access private repositories.

**Comment by Maximinodotpy** [comment]
Hey Thank you for taking the time and pointing that out!

For now I will only make it so the exception is handled because I havent figured out login when cloning and pulling and changing this means the plugin only works for Github Repos.

(If you want you can take a look at the code but I obviously dont expect you to do something, your issue is help enough)
